### PR TITLE
Control Sound Variants 

### LINKED ISSUE #1064: Control Sound Variants
Different consoles should make different sounds, they should also make sounds if the operation failed.
I'll make the backend, Saturn can implement.

### PR DESCRIPTION
**Pull request by duzos**
closes #1064 

Datapacks can define custom control sounds for Console Types
*( notice - NOT variants )*

All controls now return a `Result` which changes what sound is played, whether its a success, etc

All current controls have properly implemented fallback sounds & result returns.

### CODE REVIEW

**Comment by duzos** [comment]
wait for @DrTheodor review b4 merge

File: src/main/java/dev/amble/ait/core/blockentities/control/ControlBlockEntity.java [hunk 1]
```diff
@@ -82,8 +83,35 @@ public boolean run(ServerPlayerEntity user, boolean isMine) {
...
+        this.getConsole().ifPresent(console -> this.getWorld().playSound(null, pos, this.control.getSound(console.getTypeSchema(), result), SoundCategory.BLOCKS, 0.7f, 1f));
+
+        return result.isSuccess();
+    }
+
+    /**
+     * Finds the nearest console to this block
+     * @return The console block entity
+     */
+    public Optional<ConsoleBlockEntity> getConsole() {
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/blockentities/control/ControlBlockEntity.java:97]: ow ow ow ow ow

File: src/main/java/dev/amble/ait/core/tardis/control/sound/ControlSound.java [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+ * @param consoleId The identifier of the console that this sound is for
+ * @param successId The identifier of the sound that is played when the control is successful
+ * @param altId The identifier of the sound that is played when the control fails OR a value is switched
+ * @see Control
+ * @see ConsoleTypeSchema
+ * @author duzo
+ */
+public record ControlSound(Identifier controlId, Identifier consoleId, Identifier successId, Identifier altId) implements Identifiable {
+    public static final Codec<ControlSound> CODEC = RecordCodecBuilder.create(instance -> instance.group(
+            Identifier.CODEC.fieldOf("control_id").forGetter(ControlSound::controlId),
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/sound/ControlSound.java:38]: imo, itd be better to omit the `_id` suffix from `control_id` and `console_id`

File: src/main/java/dev/amble/ait/core/tardis/control/sound/ControlSound.java [hunk 3]
```diff
@@ -0,0 +1,101 @@
...
+
+        return sfx;
+    }
+
+    public static ControlSound forFallback(Identifier controlId, SoundEvent success, SoundEvent alt) {
+        return new ControlSound(controlId, AITMod.id("fallback"), success.getId(), alt.getId());
+    }
+
+    public static Identifier mergeIdentifiers(Identifier controlId, Identifier consoleId) {
+        return new Identifier(controlId.getNamespace(), controlId.getPath() + "_" + consoleId.getPath());
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/sound/ControlSound.java:85]: that feels weird but ill allow it

File: src/main/java/dev/amble/ait/core/tardis/control/sound/ControlSoundRegistry.java [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+        // iterate through to find matching
+        for (ControlSound sound : this.REGISTRY.values()) {
+            if (sound.controlId().equals(controlId) && sound.consoleId().equals(consoleId)) {
+                return sound;
+            }
+        }
+
+        // double iteration - wow
+        for (ControlSound sound : this.REGISTRY.values()) {
+            if (sound.controlId().equals(controlId) && sound.consoleId().equals(AITMod.id("fallback"))) {
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/sound/ControlSoundRegistry.java:75]: why not just
```
for (ControlSound sound : this.REGISTRY.values()) {
      if (sound.controlId().equals(controlId) && (sound.consoleId().equals(consoleId) || sound.consoleId().equals(AITMod.id("fallback")))) {
          return sound;
      }
  }
```

also, you should probably put the "fallback" id in a static final field

File: src/main/java/dev/amble/ait/core/tardis/control/sound/ControlSound.java (hunk 3 above)
Comment (DrTheodor) [reply src/main/java/dev/amble/ait/core/tardis/control/sound/ControlSound.java:85]: wait a minute
am i bonkers or this should be the other way around

if you have `data/ait/control_sounds/coral_monitor.json` then shouldnt the id be `new Identifier(consoleId.getNamespace(), consoleId.getPath() + "_" + controlId.getPath())`

**Review by DrTheodor — CHANGES_REQUESTED** [review]

File: src/main/java/dev/amble/ait/core/blockentities/control/ControlBlockEntity.java (hunk 1 above)
Comment (DrTheodor) [reply src/main/java/dev/amble/ait/core/blockentities/control/ControlBlockEntity.java:97]: this feels like a performance sinkhole

Comment (DrTheodor) [reply src/main/java/dev/amble/ait/core/blockentities/control/ControlBlockEntity.java:97]: and either way, its kinda weird to base the sound for a block entity defined by its position to the closest console

maybe make it so the block entity saves the console schema from the control it has been copied from? or just get the first console in the list?

File: src/main/java/dev/amble/ait/core/tardis/control/sound/ControlSound.java (hunk 3 above)
Comment (DrTheodor) [reply src/main/java/dev/amble/ait/core/tardis/control/sound/ControlSound.java:85]: Alsooo, ive just realised, this will be a bit funny with addon consoles or controls since one namespace is just getting thrown out.

What you can do is make the id be like
`<console namespace>:idontrememberwhatwashere/<console path>/<control namespace>/<control path>`

This will also ensure that we dont get any slashes in the id if some addon dev (or we ourselves) decide to make an id with a slash in it (e.g. `ait:console/whatever/some_console` - will crash, because you cant have slashes in the file name... Or it just wont detect the file at all.)

File: src/main/java/dev/amble/ait/core/tardis/control/sound/ControlSoundRegistry.java (hunk 4 above)
Comment (DrTheodor) [reply src/main/java/dev/amble/ait/core/tardis/control/sound/ControlSoundRegistry.java:75]: And now that i think of it, you shouldnt really have something hardcoded named "fallback"
You probably want to have a default or an empty value (optional, nulls, whatever) that will be qualified as one.

Basically "fallback" should be an alias to something not inherently fallback
For example how we do for the exterior schemas in `TardisBuilder` and the registries.

File: src/main/java/dev/amble/ait/core/blockentities/control/ControlBlockEntity.java [hunk 5]
```diff
@@ -35,7 +38,9 @@ public void writeNbt(NbtCompound nbt) {
         super.writeNbt(nbt);
 
         if (this.getControl() != null)
-            nbt.putString(ControlBlockItem.CONTROL_ID_KEY, this.getControl().getId().toString());
+            nbt.putString(ControlBlockItem.CONTROL_ID_KEY, this.getControl().id().toString());
+        if (this.getConsoleType() != null)
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/blockentities/control/ControlBlockEntity.java:42]: line breaks please

File: src/main/java/dev/amble/ait/core/blockentities/control/ControlBlockEntity.java [hunk 6]
```diff
@@ -54,6 +61,14 @@ public void readNbt(NbtCompound nbt) {
     public Control getControl() {
         return this.control;
     }
+    public ConsoleTypeSchema getConsoleType() {
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/blockentities/control/ControlBlockEntity.java:64]: line breaks please

File: src/main/java/dev/amble/ait/core/blockentities/control/ControlBlockEntity.java [hunk 7]
```diff
@@ -63,6 +78,14 @@ public void setControlId(Identifier id) {
 
         this.control = found.get();
     }
+    public void setConsoleId(Identifier id) {
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/blockentities/control/ControlBlockEntity.java:81]: line breaks please

File: src/main/java/dev/amble/ait/core/item/control/ControlBlockItem.java [hunk 8]
```diff
@@ -52,4 +56,12 @@ public static Optional<Identifier> findControlId(ItemStack stack) {
 
         return Optional.of(new Identifier(stack.getOrCreateNbt().getString(CONTROL_ID_KEY)));
     }
+    public static Optional<Identifier> findConsoleTypeId(ItemStack stack) {
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/item/control/ControlBlockItem.java:59]: line breaks please

File: src/main/java/dev/amble/ait/core/tardis/control/impl/AutoPilotControl.java [hunk 9]
```diff
@@ -13,22 +13,20 @@
...
         super.runServer(tardis, player, world, console, leftClick);
 
         boolean autopilot = tardis.travel().autopilot();
         tardis.travel().autopilot(!autopilot);
 
-        SoundEvent toggleSound = autopilot ? AITSounds.PROTOCOL_116_OFF : AITSounds.PROTOCOL_116_ON;
-        world.playSound(null, console, toggleSound, SoundCategory.BLOCKS, 1.0F, 1.0F);
-
-        return true;
+        return !autopilot ? Result.SUCCESS : Result.SUCCESS_ALT;
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/impl/AutoPilotControl.java:29]:
```java
return autopilot ? Result.SUCCESS_ALT : Result.SUCCESS
```

File: src/main/java/dev/amble/ait/core/tardis/control/impl/DoorLockControl.java [hunk 10]
```diff
@@ -7,43 +7,25 @@
...
 
-        boolean isRenaissance = false;
-        if (world.getBlockEntity(console) instanceof ConsoleBlockEntity consoleBlockEntity)
-            isRenaissance = isRenaissanceVariant(consoleBlockEntity);
-
-        this.soundEvent = isRenaissance ? AITSounds.RENAISSANCE_LOCK_ALT : AITSounds.DOOR_LOCK;
-
         tardis.door().interactToggleLock(player);
-        return true;
+        return !tardis.door().locked() ? Result.SUCCESS : Result.SUCCESS_ALT;
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/impl/DoorLockControl.java:24]:
```java
return tardis.door().locked() ? Result.SUCCESS_ALT : Result.SUCCESS
```

File: src/main/java/dev/amble/ait/core/tardis/control/impl/HADSControl.java [hunk 11]
```diff
@@ -11,18 +12,19 @@
...
     }
 
     @Override
-    public boolean runServer(Tardis tardis, ServerPlayerEntity player, ServerWorld world, BlockPos console, boolean leftClick) {
+    public Result runServer(Tardis tardis, ServerPlayerEntity player, ServerWorld world, BlockPos console, boolean leftClick) {
         super.runServer(tardis, player, world, console, leftClick);
 
         tardis.alarm().toggle();
-        return true;
+        return !tardis.alarm().enabled().get() ? Result.SUCCESS : Result.SUCCESS_ALT;
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/impl/HADSControl.java:27]:
```java
return tardis.alarm().enabled().get() ? Result.SUCCESS_ALT : Result.SUCCESS
```

File: src/main/java/dev/amble/ait/core/tardis/control/impl/HailMaryControl.java [hunk 12]
```diff
@@ -30,7 +32,7 @@ public boolean runServer(Tardis tardis, ServerPlayerEntity player, ServerWorld w
                 ? Text.translatable("tardis.message.control.hail_mary.engaged")
                 : Text.translatable("tardis.message.control.hail_mary.disengaged"), true);
 
-        return true;
+        return !tardis.stats().hailMary().get() ? Result.SUCCESS : Result.SUCCESS_ALT;
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/impl/HailMaryControl.java:35]:
```java
return tardis.stats().hailMary().get() ? Result.SUCCESS_ALT : Result.SUCCESS;
```

File: src/main/java/dev/amble/ait/core/tardis/control/impl/HandBrakeControl.java [hunk 13]
```diff
@@ -64,12 +56,12 @@ public boolean runServer(Tardis tardis, ServerPlayerEntity player, ServerWorld w
             }
         }
 
-        return true;
+        return !handbrake ? Result.SUCCESS : Result.SUCCESS_ALT;
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/impl/HandBrakeControl.java:59]:
```java
return handbrake ? Result.SUCCESS_ALT : Result.SUCCESS;
```

File: src/main/java/dev/amble/ait/core/tardis/control/impl/HandBrakeControl.java [hunk 14]
```diff
@@ -64,12 +56,12 @@ public boolean runServer(Tardis tardis, ServerPlayerEntity player, ServerWorld w
...
     }
 
     @Override
-    public SoundEvent getSound() {
-        return this.soundEvent;
+    public SoundEvent getFallbackSound() {
+        return AITSounds.HANDBRAKE_UP;
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/impl/HandBrakeControl.java:64]: maybe it shouldnt do this..?

File: src/main/java/dev/amble/ait/core/tardis/control/impl/RandomiserControl.java [hunk 15]
```diff
@@ -52,7 +52,7 @@ private void messagePlayer(ServerPlayerEntity player, TravelHandler travel) {
         player.sendMessage(text, true);
     }
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/impl/RandomiserControl.java:53]: line break riiight here please

File: src/main/java/dev/amble/ait/core/tardis/control/impl/RefuelerControl.java [hunk 16]
```diff
@@ -2,47 +2,42 @@
...
         if (tardis.travel().getState() == TravelHandlerBase.State.LANDED && tardis.travel().handbrake()) {
             tardis.setRefueling(!tardis.isRefueling());
 
-            if (tardis.isRefueling())
-                TardisDesktop.playSoundAtConsole(tardis.asServer().getInteriorWorld(), console, AITSounds.ENGINE_REFUEL, SoundCategory.BLOCKS, 10,
-                        1);
-
-
-            return true;
+            return !tardis.isRefueling() ? Result.SUCCESS : Result.SUCCESS_ALT;
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/impl/RefuelerControl.java:33]:
```java
return tardis.isRefueling() ? Result.SUCCESS_ALT : Result.SUCCESS;
```

File: src/main/java/dev/amble/ait/core/tardis/control/impl/ShieldsControl.java [hunk 17]
```diff
@@ -46,16 +37,7 @@ public boolean runServer(Tardis tardis, ServerPlayerEntity player, ServerWorld w
...
-        if (isRenaissance) {
-            this.soundEvent = leftClick ? AITSounds.RENAISSANCE_SHIELDS_ALTALT : AITSounds.RENAISSANCE_SHIELDS_ALT;
-        } else if (isCoral) {
-            this.soundEvent = leftClick ? AITSounds.CORAL_SHIELDS_ALTALT : AITSounds.CORAL_SHIELDS_ALT;
-        } else {
-            this.soundEvent = leftClick ? AITSounds.SHIELDS : AITSounds.HANDBRAKE_LEVER_PULL;
-        }
-
-        return true;
+        return !leftClick ? Result.SUCCESS :  Result.SUCCESS_ALT;
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/impl/ShieldsControl.java:40]: ....you guessed it

File: src/main/java/dev/amble/ait/core/tardis/control/impl/ShieldsControl.java [hunk 18]
```diff
@@ -64,23 +46,7 @@ protected SubSystem.IdLike requiredSubSystem() {
...
-    }
-
-    private boolean isCoralVariant(ConsoleBlockEntity consoleBlockEntity) {
-        return consoleBlockEntity.getVariant() instanceof CoralVariant ||
-                consoleBlockEntity.getVariant() instanceof WhiteCoralVariant ||
-                consoleBlockEntity.getVariant() instanceof CoralSithVariant ||
-                consoleBlockEntity.getVariant() instanceof BlueCoralVariant ||
-                consoleBlockEntity.getVariant() instanceof CoralDecayedVariant;
+    public SoundEvent getFallbackSound() {
+        return AITSounds.HANDBRAKE_LEVER_PULL;
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/impl/ShieldsControl.java:50]: shields control dont have their own sound?

File: src/main/java/dev/amble/ait/core/tardis/control/impl/RefreshmentControl.java [hunk 19]
```diff
@@ -41,7 +39,7 @@ public boolean requiresPower() {
     }
 
     @Override
-    public SoundEvent getSound() {
+    public SoundEvent getFallbackSound() {
         return AITSounds.ALARM;
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/impl/RefreshmentControl.java:43]: doesnt have its own sound?

File: src/main/java/dev/amble/ait/core/tardis/control/impl/ThrottleControl.java [hunk 20]
```diff
@@ -52,11 +52,11 @@ public boolean runServer(Tardis tardis, ServerPlayerEntity player, ServerWorld w
         if (travel.getState() == TravelHandler.State.DEMAT)
             tardis.sequence().setActivePlayer(player);
 
-        return true;
+        return !player.isSneaking() ? Result.SUCCESS : Result.SUCCESS_ALT;
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/impl/ThrottleControl.java:55]: you know the drill

Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/impl/ThrottleControl.java:55]: you know the drill

File: src/main/java/dev/amble/ait/core/tardis/control/impl/ThrottleControl.java [hunk 21]
```diff
@@ -52,11 +52,11 @@ public boolean runServer(Tardis tardis, ServerPlayerEntity player, ServerWorld w
...
     }
 
     @Override
-    public SoundEvent getSound() {
+    public SoundEvent getFallbackSound() {
         return AITSounds.DEMAT_LEVER_PULL;
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/impl/ThrottleControl.java:60]: should probably refactor the sound name to be "THROTTLE" not "DEMAT_LEVER" just to avoid confusion

Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/impl/ThrottleControl.java:60]: should probably refactor the sound name to be "THROTTLE" not "DEMAT_LEVER" just to avoid confusion

File: src/main/java/dev/amble/ait/core/tardis/control/impl/VisualiserControl.java [hunk 22]
```diff
@@ -53,7 +53,7 @@ protected SubSystem.IdLike requiredSubSystem() {
     }
 
     @Override
-    public SoundEvent getSound() {
+    public SoundEvent getFallbackSound() {
         return AITSounds.RENAISSANCE_ANTI_GRAV_ALT;
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/impl/VisualiserControl.java:57]: no own sound?

Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/impl/VisualiserControl.java:57]: no own sound?

Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/impl/VisualiserControl.java:57]: no own sound?

File: src/main/java/dev/amble/ait/core/tardis/control/impl/pos/IncrementControl.java [hunk 23]
```diff
@@ -8,43 +8,33 @@
...
-
         if (!leftClick) {
             IncrementManager.nextIncrement(tardis);
         } else {
             IncrementManager.prevIncrement(tardis);
         }
 
         messagePlayerIncrement(player, tardis);
-        return true;
+        return !leftClick ? Result.SUCCESS : Result.SUCCESS_ALT;
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/impl/pos/IncrementControl.java:32]: same as always

File: src/main/java/dev/amble/ait/core/tardis/control/impl/waypoint/EjectWaypointControl.java [hunk 24]
```diff
@@ -15,8 +17,12 @@ public EjectWaypointControl() {
     }
 
     @Override
-    public boolean runServer(Tardis tardis, ServerPlayerEntity player, ServerWorld world, BlockPos console, boolean leftClick) {
+    public Result runServer(Tardis tardis, ServerPlayerEntity player, ServerWorld world, BlockPos console, boolean leftClick) {
         tardis.waypoint().spawnItem(console);
-        return false;
+        return Result.SUCCESS;
+    }
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/impl/waypoint/EjectWaypointControl.java:23]: line breaks please

File: src/main/java/dev/amble/ait/core/tardis/control/impl/waypoint/SetWaypointControl.java [hunk 25]
```diff
@@ -16,13 +18,17 @@ public SetWaypointControl() {
...
+    public Result runServer(Tardis tardis, ServerPlayerEntity player, ServerWorld world, BlockPos console, boolean leftClick) {
         super.runServer(tardis, player, world, console, leftClick);
 
         WaypointHandler waypoints = tardis.waypoint();
 
         waypoints.setDestination();
         waypoints.spawnItem(console);
-        return true;
+        return Result.SUCCESS;
+    }
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/impl/waypoint/SetWaypointControl.java:29]: line breaks please

File: src/main/java/dev/amble/ait/core/tardis/control/sound/ControlSound.java [hunk 26]
```diff
@@ -0,0 +1,111 @@
...
+     * @param consoleId Id of the console
+     * @return Merged identifier
+     */
+    public static Identifier mergeIdentifiers(Identifier controlId, Identifier consoleId) {
+        return Identifier.of(consoleId.getNamespace(), consoleId.getPath() + "/" + controlId.getNamespace() + "/" + controlId.getPath());
+    }
+
+    public static ControlSound fromInputStream(InputStream stream) {
+        return fromJson(JsonParser.parseReader(new InputStreamReader(stream)).getAsJsonObject());
+    }
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/sound/ControlSound.java:100]: line breaks please

File: src/main/java/dev/amble/ait/core/tardis/control/sound/ControlSoundRegistry.java [hunk 27]
```diff
@@ -0,0 +1,105 @@
...
+import dev.amble.ait.AITMod;
+import dev.amble.ait.core.AITSounds;
+import dev.amble.ait.core.tardis.control.Control;
+import dev.amble.ait.core.tardis.control.impl.*;
+import dev.amble.ait.data.schema.console.ConsoleTypeSchema;
+
+public class ControlSoundRegistry extends SimpleDatapackRegistry<ControlSound> {
+    private static final ControlSoundRegistry instance = new ControlSoundRegistry();
+
+    public static final SimpleRegistry<ControlSound> FALLBACKS = FabricRegistryBuilder
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/sound/ControlSoundRegistry.java:22]: this aint right
you shouldnt mix amble registries with vanilla ones

File: src/main/java/dev/amble/ait/AITMod.java [hunk 28]
```diff
@@ -164,6 +165,7 @@ public void onInitialize() {
                 ItemOpinionRegistry.getInstance(),
                 DrinkRegistry.getInstance()
         );
+        ControlSoundRegistry.init();
```
[the remark this answers is not in the document]
Comment (DrTheodor) [reply src/main/java/dev/amble/ait/AITMod.java:168]: yep, just checked, this line of code should be a bit higher together with all the other amble registries

File: src/main/java/dev/amble/ait/core/tardis/control/sound/ControlSoundRegistry.java [hunk 29]
```diff
@@ -0,0 +1,105 @@
...
+            return possible;
+        }
+
+        return this.fallback();
+    }
+    public ControlSound get(ConsoleTypeSchema console, Control control) {
+        return this.get(console.id(), control.id());
+    }
+
+    public static void init() {
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/sound/ControlSoundRegistry.java:95]: all the defaults should be in the `defaults` method

File: src/main/resources/data/ait/control_sounds/coral_monitor.json
Comment (DrTheodor) [inline src/main/resources/data/ait/control_sounds/coral_monitor.json:1]: the file is a wrong location
according to the `mergeIdentifiers` it should be at `ait/control_sounds/coral/ait/monitor.json` or someting along those lines

File: src/main/resources/data/ait/control_sounds/coral_shields.json
Comment (DrTheodor) [inline src/main/resources/data/ait/control_sounds/coral_shields.json:1]: the file is a wrong location
according to the `mergeIdentifiers` it should be at `ait/control_sounds/coral/ait/shields.json` or someting along those lines

**Review by DrTheodor — CHANGES_REQUESTED** [review]

File: src/main/java/dev/amble/ait/core/tardis/control/impl/HandBrakeControl.java (hunk 14 above)
Comment (duzos) [reply src/main/java/dev/amble/ait/core/tardis/control/impl/HandBrakeControl.java:64]: do what

File: src/main/java/dev/amble/ait/core/tardis/control/sound/ControlSoundRegistry.java (hunk 29 above)
Comment (duzos) [reply src/main/java/dev/amble/ait/core/tardis/control/sound/ControlSoundRegistry.java:95]: can't, register froze

File: src/main/resources/data/ait/control_sounds/coral_monitor.json
Comment (duzos) [reply src/main/resources/data/ait/control_sounds/coral_monitor.json:1]: doesn't rlly matter where it goes

File: src/main/java/dev/amble/ait/core/tardis/control/impl/RefreshmentControl.java (hunk 19 above)
Comment (duzos) [reply src/main/java/dev/amble/ait/core/tardis/control/impl/RefreshmentControl.java:43]: nope

File: src/main/java/dev/amble/ait/core/tardis/control/impl/VisualiserControl.java (hunk 22 above)
Comment (duzos) [reply src/main/java/dev/amble/ait/core/tardis/control/impl/VisualiserControl.java:57]: nope

File: src/main/java/dev/amble/ait/AITMod.java (hunk 28 above)
[the remark this answers is not in the document]
Comment (duzos) [reply src/main/java/dev/amble/ait/AITMod.java:168]: it inits the simpleregistry so needs own init method

File: src/main/java/dev/amble/ait/core/tardis/control/sound/ControlSound.java [hunk 30]
```diff
@@ -0,0 +1,112 @@
...
+ * @see Control
+ * @see ConsoleTypeSchema
+ * @author duzo
+ */
+public record ControlSound(Identifier controlId, Identifier consoleId, Identifier successId, Identifier altId) implements Identifiable {
+    public static final Codec<ControlSound> CODEC = RecordCodecBuilder.create(instance -> instance.group(
+            Identifier.CODEC.fieldOf("control").forGetter(ControlSound::controlId),
+            Identifier.CODEC.fieldOf("console").forGetter(ControlSound::consoleId),
+            Identifier.CODEC.fieldOf("success_sound").forGetter(ControlSound::successId),
+            Identifier.CODEC.optionalFieldOf("alt_sound", Identifier.of("", "")).forGetter(ControlSound::altId)
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/control/sound/ControlSound.java:41]: its probably a better idea to use `SoundEvents.INTENTIONALLY_EMPTY` here or an optional

File: src/main/resources/assets/ait/sounds/controls.zip
Comment (DrTheodor) [inline src/main/resources/assets/ait/sounds/controls.zip:1]: not sure this should be here

File: src/main/resources/data/ait/control_sounds/renaissance/renaissance_shields.json [hunk 31]
```diff
@@ -0,0 +1,6 @@
+{
+  "control": "ait:shields",
+  "console": "ait:console/renaissance",
+  "success_sound": "ait:controls/renaissance_shieldsalt",
+  "alt_sound": "ait:controls/renaissance_shieldsaltalt"
```
Comment (DrTheodor) [inline src/main/resources/data/ait/control_sounds/renaissance/renaissance_shields.json:5]:
```diff
- ait:controls/renaissance_shieldsaltalt
+ ait:controls/renaissance_shields_alt
```

File: src/main/resources/data/ait/control_sounds/renaissance/renaissance_shields.json [hunk 32]
```diff
@@ -0,0 +1,6 @@
+{
+  "control": "ait:shields",
+  "console": "ait:console/renaissance",
+  "success_sound": "ait:controls/renaissance_shieldsalt",
```
Comment (DrTheodor) [inline src/main/resources/data/ait/control_sounds/renaissance/renaissance_shields.json:4]:
```diff
- ait:controls/renaissance_shieldsalt
+ ait:controls/renaissance_shields
```

**Review by DrTheodor — CHANGES_REQUESTED** [review]
another thing id like to point out is the json's identifiers, for example `src/main/resources/data/ait/control_sounds/copper/copper_alarm.json`
why does it repeat the console name twice?

i know this is a bit of a stretch but if were gonna be keeping backwards compatibility from now on better do it good and consistent from the start

File: src/main/java/dev/amble/ait/core/tardis/control/sound/ControlSound.java (hunk 30 above)
Comment (duzos) [reply src/main/java/dev/amble/ait/core/tardis/control/sound/ControlSound.java:41]: instead of checking for missing sound i'll also check for intentionally empty then

File: src/main/java/dev/amble/ait/core/tardis/handler/travel/ProgressiveTravelHandler.java [hunk 33]
```diff
@@ -151,7 +151,7 @@ public void increaseSpeed() {
 
     public void decreaseSpeed() {
         if (this.getState() == State.LANDED && this.speed.get() == 1)
-            this.tardis.getDesktop().playSoundAtEveryConsole(AITSounds.RENAISSANCE_HANDBRAKE_ALTALT, SoundCategory.AMBIENT);
+            this.tardis.getDesktop().playSoundAtEveryConsole(AITSounds.DIRECTION, SoundCategory.AMBIENT);
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/tardis/handler/travel/ProgressiveTravelHandler.java:154]: are you sure the sound you want to use is DIRECTION and not HANDBRAKE_*?

File: src/main/java/dev/amble/ait/core/tardis/control/sound/ControlSound.java (hunk 30 above)
Comment (DrTheodor) [reply src/main/java/dev/amble/ait/core/tardis/control/sound/ControlSound.java:41]: or use an optional
in which case you just gotta check if its empty

**Review by DrTheodor — CHANGES_REQUESTED** [review]

**Review by Loqor — APPROVED** [review]
Good code throughout, the CODEC is fantastic (excluding the missing optionals like Theo said), and I think overall the replacement of getId() for id() is better in the long run. Approved.

File: src/main/java/dev/amble/ait/core/tardis/handler/travel/ProgressiveTravelHandler.java (hunk 33 above)
Comment (Saturnorsomthing) [reply src/main/java/dev/amble/ait/core/tardis/handler/travel/ProgressiveTravelHandler.java:154]: direction is more of a "click" sound which sounds nicer when you push the handbrake all the way back

Comment (Saturnorsomthing) [reply src/main/java/dev/amble/ait/core/tardis/handler/travel/ProgressiveTravelHandler.java:154]: throttle*
