### PR TITLE
Fix some controls being interact-able during growth state

### LINKED ISSUE #1525: [1.2.3] Protocol 515 usable in growth TARDIS
### What happened?

Protocol 515 can be used in a growth TARDIS with an engine + console to move it

### Version

1.2.1

### Build number & branch

_No response_

### Logs & screenshots

N/A

### I've checked the reported issues...

- [x] ...and this issue was not reported before.

### PR DESCRIPTION
**Pull request by Mansarde**
## About the PR
This PR prevents interact-ability of the console controls during a TARDIS' growth-state.

fixes #1525 

## Why / Balance
The console controls should not be interactable during growth mode, as the TARDIS has not yet fully formed.

## Technical details
There is a guard-clause early on in the control-code, which returns false if the TARDIS is in the growth-state (so that neither the sound for a control plays, nor a missing-subsystem message is displayed, etc.).

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://amblelabs.github.io/ait-wiki/guidelines).
- [X] It does not require an ingame showcase.

**Changelog**
:cl:
- fix: controls were interact-able during growth state, but shouldn't

### CODE REVIEW

File: src/main/java/dev/amble/ait/core/entities/ConsoleControlEntity.java [hunk 1]
```diff
@@ -378,7 +378,9 @@ public void subtractDurability(float durability) {
     }
 
     public boolean run(PlayerEntity player, World world, boolean leftClick) {
-        if (world.isClient())
+        Tardis tardis = this.tardis().get();
+
+        if (world.isClient() || tardis.isGrowth())
```
Comment (Mansarde) [inline src/main/java/dev/amble/ait/core/entities/ConsoleControlEntity.java:383]: I whould probably put the growth check in its own condition.
But I wasn't sure how you would want it, so I opted for keeping it compact.

Let me know if you want this to be separate. :)

Comment (DrTheodor) [reply src/main/java/dev/amble/ait/core/entities/ConsoleControlEntity.java:383]: nitpick: you should first do a `isClient` check and only then get the tardis.
the cost of getting the tardis is more than checking if the world is on client

File: src/main/java/dev/amble/ait/core/blockentities/control/ControlBlockEntity.java [hunk 2]
```diff
@@ -100,6 +100,9 @@ public boolean run(ServerPlayerEntity user, boolean isMine) {
         if (!(found.get() instanceof ServerTardis tardis))
             return false;
 
+        if (found.get().isGrowth())
```
Comment (DrTheodor) [inline src/main/java/dev/amble/ait/core/blockentities/control/ControlBlockEntity.java:103]: i feel like this could be moved inside `Control#canRun`

File: src/main/java/dev/amble/ait/core/entities/ConsoleControlEntity.java (hunk 1 above)
Comment (DrTheodor) [reply src/main/java/dev/amble/ait/core/entities/ConsoleControlEntity.java:383]: also check my previous comment on ``ControlBlockEntity`

**Review by DrTheodor — CHANGES_REQUESTED** [review]

File: src/main/java/dev/amble/ait/core/blockentities/control/ControlBlockEntity.java (hunk 2 above)
Comment (Mansarde) [reply src/main/java/dev/amble/ait/core/blockentities/control/ControlBlockEntity.java:103]: Ok, I can do that.
The reason I put it into `run` for both `ControlBlockEntity` and `ConsoleControlEntity` was because in the latter I wanted it to prevent the secret music from playing if the TARDIS is still in growth:
https://github.com/amblelabs/ait/blob/99da8d9b0773293e7b313469260539c21b95fa05/src/main/java/dev/amble/ait/core/entities/ConsoleControlEntity.java#L386-L388

But I could move the secret music down, right after `canRun` instead I suppose.
Will do that and test it. :)

**Comment by Mansarde** [comment]
@DrTheodor Ok, I've moved the check to the parent class and restored the changes in the previous two console classes, which should resolve both of your requested changes.

**Review by DrTheodor — APPROVED** [review]
LGTM
